### ISSUE TITLE
Cannot read property 'scrollTop' of undefined

### ISSUE THREAD

**Issue by Ahsanmughal** [hafizbilal112/ion-fab-button#4]
Hey I am using the ion-fab directive, that works very nice independently.when i am using inside my project it gives this error **Cannot read property 'scrollTop' of undefined** while scrolling the page down.

Hope you will help.

**Comment by bilalrazamoon** [comment]
Did you put fab-scroll-container directive (attribute) to scrollable container.

**Comment by Ahsanmughal** [comment]
yes i did the same.and i also find the solution of this problem.

you can find the value of scrollTop by $ionicScrollDelegate dependency.

$ionicScrollDelegate.getScrollPosition().top;

**Comment by DavidVc30** [comment]
@Ahsanmughal

I'm having the same issue with this (otherwise fine) directive. 

Will you share a code snippet of the solution you found?

**Comment by bilalrazamoon** [comment]
@DavidVc30 I've fixed bug in master
https://github.com/hafizbilal112/ion-fab/commit/72a2c0b34bb00c789cecba2cd405548a5dbbf7e3

**Comment by DavidVc30** [comment]
Thx! :-)
